before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: jndqabpMUGan2SHz4ghp7OXk4xght57mM4CbRYmQPhXyYRGvjuxQsl/5doDX3nahANowIpwNkiyKnSKMuBv4Z+bPvBuACk9vcst7+NhDnrW0cbRYU12pPXyGB3n71yM5O0fs5+Mxj3a6jqw+7mQsSEKtRqVyJzDVKEMzE9Kq/+eUnVEXPuC9qImAyL76iGTcmeYCudz0e7ReN0BNNz86v+SUrhPk/wgPDInUxgG+BLjoyibbUTOMRznfNVgCdhkMQjP8GOl3kCniPzGi1RIQAYEAbOCqUhI5m3i77onqQXFxfMlsuWSuthilQs8y7d+mdoOLbwj12tdBXk0ig2N9VjBeOWjr+yNkxrcl4MA+ygOkAoXhONmgcSEwoImpZcZ4rDuxIpJYnb30D4qAG/m2/ybuqVEuQvz72sdvEyu+U+cYFgBsVfc5AWgBKS4lP1a5wHYh+iw3t4TJoo+iOu0nKZrB2aZyGofT/Dn0TFAutCPYjCoRXHNy8jHevfroJn48AulHGSW6Fu5v55E+Jgxx2vI8O3bijDPBnjVEgR/XrsqintUiK3YbX5sH5vYdNxjnUJN36yqd/l60XMEXuhanNN6M0TZ4I4BkeVIvqkWzQl6YQ51fIVWu/utjaUoL7g16NNZVaJAbWI29Lb5VcSaoX3xBns3wL7kGuziv7Gv2z6w= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
